server:
  port: 8081
spring:
  application:
    name: dp
  rabbitmq:
    host: 47.122.134.229
    port: 5672
    username: ylz
    password: ylz021129
    virtual-host: /
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.122.134.229:3306/dp?useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: dp
    password: 021129
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始连接数
      initial-size: 5
      # 最小连接数
      min-idle: 5
      # 最大连接数
      max-active: 20
      # 获取连接超时时间
      max-wait: 60000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      # 配置检测连接是否有效
      validation-query: SELECT 1
      # 空闲时检测连接有效性
      test-while-idle: true
      # 获取连接时检测有效性
      test-on-borrow: false
      # 归还连接时检测有效性
      test-on-return: false
      # 开启PSCache
      pool-prepared-statements: true
      # PSCache大小
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    client-name: dp-redis
    host: 47.122.134.229
    # host: 192.168.11.20
    port: 6379
    # password: yunliuzhu202212900436
    password: ylz021129
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: NON_NULL # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.dp.entity # 别名扫描包
logging:
  level:
    '[com.dp]': debug


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true  
  metrics:
    tags:
      application: ${spring.application.name}
      redis-host: ${spring.redis.host}
      redis-port: ${spring.redis.port}
    enable:
      redis: true
    distribution:
      percentiles-histogram:
        redis: true
