@host = http://localhost:8080

@token = a45ac19e69354fb88bb65eeb6aa4d2ab



POST {{host}}/api/voucher-order/seckill/11
Authorization: {{token}}

#### 秒杀下单
POST {{host}}/api/voucher/seckill
Content-Type: application/json

{
    "shopId": 3,
    "title": "100元代金券",
    "subTitle": "周一至周五均可使用",
    "rules": "全场通用\\n无需预约\\n可无限叠加\\不兑现\\不找零",
    "payValue": 8000,
    "actualValue": 10000,
    "type": 1,
    "stock": 100,
    "beginTime": "2025-03-20T10:00:00",
    "endTime": "2025-04-20T10:00:00"
}
